version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - GIN_MODE=release
      - PORT=8001
    networks:
      - deepwiki-network

  web:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    depends_on:
      - api
    networks:
      - deepwiki-network

networks:
  deepwiki-network:
    driver: bridge 